<template>
  <div>
    <h1>disclaimer</h1>
  </div>
  Disclaimer
  The information on this website is intended for general informational purposes only. Luna’s Wild Rides makes every
  effort to ensure that the information on the website is correct, complete, and up-to-date, but makes no warranties or
  representations of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or
  availability with respect to the website or the information, products, services, or related graphics on the website, for
  any purpose.

  Any reliance you place on such information is therefore strictly at your own risk. Luna’s Wild Rides shall not be liable
  for any loss or damage, including but not limited to indirect or consequential loss, or any loss or damage whatsoever
  arising from loss of data or profits arising out of, or in connection with, the use of this website.

  The website of Luna’s Wild Rides contains links to other websites that are not under the control of Luna’s Wild Rides.
  Luna’s Wild Rides has no control over the nature, content, and availability of those sites. The inclusion of any links
  does not necessarily imply a recommendation or endorse the views expressed within them. The use of such linked websites
  is at the user’s own risk.

  This website uses Google Analytics, a web analytics service provided by Google Inc. (“Google”). Google Analytics uses
  “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The
information generated by the cookie about your use of the website (including your IP address) will be transmitted to and
stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your
use of the website, compiling reports on website activity for website operators and providing other services relating to
website activity and internet usage. Google may also transfer this information to third parties where required to do so
by law, or where such third parties process the information on Google’s behalf. By using this website, you consent to
the processing of data about you by Google in the manner and for the purposes set out above.

Luna’s Wild Rides reserves the right to change or update the content of the website at any time and without prior
notice.</template>

<script setup lang="ts">

</script>

<style scoped></style>